[package]
name = "badwords"
description = "a crate that gives you a list of bad words"
version = "0.1.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
repository = "https://github.com/ashleygwilliams/rust-badwords"
license = "MIT"

[dependencies]
